### PR TITLE
Added Audacious, Timeshift, and Shotcut (Hacktoberfest 2020)

### PR DESCRIPTION
**Pull request by actualmermaid**

### CODE REVIEW

**Comment by leomaurodesenv** [comment]
Thanks @actualmermaid ,
You forgot the end points. Please, review your commit before the merge/pull request.

**Comment by actualmermaid** [comment]
My apologies. This is now fixed, thanks.

**Comment by leomaurodesenv** [comment]
Don't worry. We are grateful for your contribution. Thank you

**Comment by 103cuong** [comment]
Hi @actualmermaid, `Audacious`, `Timeshift`, and `Shotcut` are open source projects.
Please write description with this [format](https://github.com/103cuong/awesome-linux-apps/blob/master/CONTRIBUTING.md): `[Resource Name](link) - Short description. 👏`

**Comment by actualmermaid** [comment]
Got that fixed as well! Thanks!

**Review by 103cuong — APPROVED** [review]

**Pull request merged**
